[package]
name = "risk_toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
ndarray = { version = "0.16.1", features = ["serde"] }
ndarray-linalg = { version = "0.17.0", features = ["openblas-system"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0.12"
