model_settings:
  pca_factors: 10
  risk_lookback_days: 252
  min_coverage_pct: 80

orthogonalization:
  enabled: true
  method: pca
  priority_order:
    - [US Rates, European Rates, Asian Rates]  # Rates first due to macro importance
    - [US Equity, European Equity, Asian Equity]  # Regional equity blocks
    - [Energy, Precious Metals]  # Commodities
    - [Major FX, EM FX]  # FX last as they're often driven by other factors
    - [Global Momentum, Mean Reversion]  # Style factors
    - [Carry, Liquidity]  # Market microstructure factors
  constraints:
    max_correlation: 0.3
    min_variance_explained: 0.01

factor_groups:
  # Regional Equity Factors
  - name: US Equity
    description: Major US equity indices
    assets: [ES00-USA, NQ00-USA]
    weighting: !InverseVolatility
      lookback_days: 252
    factor_type: Thematic

  - name: European Equity
    description: Major European equity indices
    assets: [FESX00-EUR, Z00-IFEU]
    weighting: !MinimumVariance
      lookback_days: 252
      constraints:
        min_weight: 0.2
        max_weight: 0.8
        sum_to_one: true
    factor_type: Thematic

  - name: Asian Equity
    description: Asian equity indices
    assets: [NIK22500-OSE]
    weighting: !Equal
    factor_type: Thematic

  # Commodity Factors
  - name: Energy
    description: Energy commodities
    assets: [CL00-USA, BRN00-IFEU, NG00-USA]
    weighting: !InverseVolatility
      lookback_days: 126
    factor_type: Thematic

  - name: Precious Metals
    description: Precious metals
    assets: [GC00-USA, SI00-USA]
    weighting: !Equal
    factor_type: Thematic

  # Fixed Income Factors
  - name: US Rates
    description: US Treasury futures across the curve
    assets: [TU00-USA, FV00-USA, TY00-USA]
    weighting: !MinimumVariance
      lookback_days: 252
      constraints:
        min_weight: 0.2
        max_weight: 0.8
        sum_to_one: true
    factor_type: Thematic

  - name: European Rates
    description: European government bond futures
    assets: [FGBS00-EUR, FGBM00-EUR, FGBL00-EUR, RLI00-IFEU]
    weighting: !MinimumVariance
      lookback_days: 252
      constraints:
        min_weight: 0.1
        max_weight: 0.4
        sum_to_one: true
    factor_type: Thematic

  - name: Asian Rates
    description: Japanese government bond futures
    assets: [JBT00-OSE, JGBS00-OSE]
    weighting: !MinimumVariance
      lookback_days: 252
      constraints:
        min_weight: 0.3
        max_weight: 0.7
        sum_to_one: true
    factor_type: Thematic

  # Currency Factors
  - name: Major FX
    description: Major currency futures vs USD
    assets: [EC00-USA, JY00-USA, BP00-USA, SFC00-USA]
    weighting: !InverseVolatility
      lookback_days: 126
    factor_type: Thematic

  - name: EM FX
    description: Emerging market currency futures
    assets: [RMB00-USA]
    weighting: !Equal
    factor_type: Thematic

  # Style Factors
  - name: Global Momentum
    description: Cross-asset momentum factor
    assets: [
      ES00-USA, NQ00-USA, FESX00-EUR, Z00-IFEU, NIK22500-OSE,
      CL00-USA, BRN00-IFEU, GC00-USA, SI00-USA
    ]
    factor_type: !Momentum
      lookback_days: 252
      skip_days: 21
    weighting: !Equal

  - name: Mean Reversion
    description: Short-term mean reversion factor
    assets: [
      ES00-USA, NQ00-USA, FESX00-EUR, Z00-IFEU,
      CL00-USA, BRN00-IFEU, GC00-USA, SI00-USA
    ]
    factor_type: !MeanReversion
      lookback_days: 10
    weighting: !Equal

  - name: Carry
    description: Cross-asset carry factor
    assets: [
      TU00-USA, FV00-USA, TY00-USA,
      FGBS00-EUR, FGBM00-EUR, FGBL00-EUR,
      JBT00-OSE, JGBS00-OSE
    ]
    factor_type: Carry
    weighting: !MinimumVariance
      lookback_days: 252
      constraints:
        min_weight: 0.1
        max_weight: 0.4
        sum_to_one: true

  - name: Liquidity
    description: Market liquidity factor
    assets: [
      ES00-USA, NQ00-USA, FESX00-EUR, Z00-IFEU,
      CL00-USA, BRN00-IFEU, GC00-USA, SI00-USA
    ]
    factor_type: !Liquidity
      volume_lookback: 21
    weighting: !InverseVolatility
      lookback_days: 126 